### ISSUE TITLE
Create PR and ISSUE templates

### ISSUE THREAD

**Issue by Kirill-Vorobyev** [nasa-gcn/.github#6]
### Description

We need to standardize how we create issue and PR artifacts.

### Links to feature design doc, conversations, mockups, etc.
![image](https://github.com/nasa-gcn/.github/assets/35638949/b3391ee3-6967-442d-9fad-02012e5333e8)

### Stakeholders
@Courey @dakota002 @swyatt7 @jak574 @lpsinger @Kirill-Vorobyev 

### Functional Requirements
Issue template should allow developers and non-developers to create a detailed Bug Report or Feature Request
Pull Request template should allow developers to fill out a form and not forget key details when submitting a PR

### Non-functional Requirements
Issue template should not take more than 5 minutes to fill out.
Pull request template should not take more than 10 minutes to fill out.

### Acceptance Criteria
When a user creates an issue, the issue template should appear automatically.
When a user submits a Pull Request, the PR template should appear automatically.

Note: currently not possible to test because this initial issue/PR will add the templates.

**Comment by lpsinger** [comment]
> Issue template should not take more than 5 minutes to fill out. Pull request template should not take more than 10 minutes to fill out.

Does that include the time to craft a commit message or to write up a reproducer for a bug?

As a matter of habit I tend to write pretty detailed PR messages that fully explain the changes and rationale. Ideally I would like a PR template that requires no more than a minute of additional data entry beyond that.

**Comment by lpsinger** [comment]
> * [ ]  This is a bug report.
> * [x]  This is a feature request.

So, we already have the https://github.com/nasa-gcn/.github/labels/bug and https://github.com/nasa-gcn/.github/labels/enhancement labels. Could we use those instead of checkboxes? It makes it easier to filter issues and PRs. Also, checklists look like to-do lists to me.

**Comment by Courey** [comment]
I like both of the templates. They look standard. 👍
